# Get the rocker image we want
FROM rocker/binder:latest

# Add packages not part of rocker/geospatial
RUN Rscript -e "install.packages('cubelyr')"
RUN Rscript -e "install.packages('exactextractr')"
RUN Rscript -e "install.packages('basemaps')"
RUN Rscript -e "install.packages('shiny')"
RUN Rscript -e "install.packages('data.table')"
RUN Rscript -e "install.packages('kableExtra')"
RUN Rscript -e "install.packages('aws.s3')"

# copy the lesson contents into the image
## WSIM lessons
# ADD m101a-wsim-gldas-acquisition.qmd /home/rstudio/
# ADD m101b-wsim-gldas-vis.qmd /home/rstudio/
# ADD m101b-wsim-vis-python.qmd /home/rstudio
## MODIS NRT LESSON
# ADD m102-lance-modis-nrt-global-flood.qmd /home/rstudio

## Copy the shiny app
# ADD /m103-nyc-lead home/rstudio

## give the rstudio user permissions on these files
# RUN chown -R rstudio /home/rstudio/

CMD ["/init"]