# Get the rocker image we want
FROM rocker/geospatial:latest

# copy the lesson contents into the image
## WSIM lessons
ADD wsim-gldas-acquisition.qmd /home/rstudio/
ADD wsim-gldas-vis.qmd /home/rstudio/
ADD wsim-vis-python.qmd /home/rstudio
## MODIS NRT LESSON
ADD lance-modis-nrt-global-flood-mcdwd-f3.qmd /home/rstudio

## Copy the shiny app
ADD /nyc_lead_dev home/rstudio

## give the rstudio user permissions on these files
RUN chown -R rstudio /home/rstudio/

# Add packages not part of rocker/geospatial
RUN Rscript -e "install.packages('cubelyr')"
RUN Rscript -e "install.packages('exactextractr')"
RUN Rscript -e "install.packages('basemaps')"
RUN Rscript -e "install.packages('shiny')"

# Python Environment
RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y python3-pip

RUN pip install exactextract
RUN pip install geopandas pyproj shapely xarray rioxarray 
RUN pip install rasterio netcdf4 h5netcdf dask bottleneck 
RUN pip install numpy pandas nc-time-axis requests
RUN pip install exactextract

CMD ["/init"]