---
title: "README"
format: gfm
---

# TOPSTSCHOOL-module-1-water

The first TOPSTSCHOOL Module on Water consists of three vignettes which cover examples of water use, safety, and anomalies such as droughts and floods. The vignettes use three datasets to walk users through lessons in accessing and analyzing data, and users will be able to adapt the code in all three examples to perform analyses including data cleaning, processing to subset to an area of interest, and creating visualizations to share what they have learned with their communities. Users will understand an Open Science workflow including accessing and citing open data. The three datasets and vignettes cover:

**Lead in New York State Schools** - Exploring lead contamination data and US Census data and lessons in data cleaning and visualization, with a discerning eye towards data limitations.

**MODIS Near Real Time flood data** - Lessons in data acquisition and analysis of recent water anomalies. 

**WSIM-GLDAS** - Exploring water anomalies using a historical dataset.



